version: '3.7'

services:
  backend:
    container_name: backend
    build: .
    image: fastapi-sqlalchemy:latest
    restart: always
    env_file:
      - .env
    network_mode: host
    ports:
      - 8005:8000

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    network_mode: host
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: postgres_data