version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    network_mode: host
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    command: bash -c "alembic revision --autogenerate && alembic upgrade head"
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
    name: postgres_data